export const FETCH_ALL_QUIZZ_REQUEST = 'FETCH_ALL_QUIZZ_REQUEST';
export const FETCH_ALL_QUIZZ_SUCCESS = 'FETCH_ALL_QUIZZ_SUCCESS';
export const FETCH_ALL_QUIZZ_FAILURE = 'FETCH_ALL_QUIZZ_FAILURE';
